# Initialisation de la base de cours pour SIAD/M2 - 2016/2017

version: '2'

services:
  postgres:
    build:
      context: ./postgre
    image: shipstone/postgres-siad2016
    container_name: postgres-db-siad2016
    ports:
      - 5432:5432
